### ISSUE TITLE
Annotation STRING (source)

### ISSUE THREAD

**Issue by lottawagner** [lottawagner/NetworkHub#1]
STRING provides ENSEMBLPROT information on their interactors. We want to get the ENSEMBLEGENE identifiers and currently match via "AnnotationDbi" and corresponding packages. STRING provides a file ([protein.aliases.v12.0.txt.gz](https://stringdb-downloads.org/download/protein.aliases.v12.0.txt.gz) that contains the annotation information as well. 

Aim: we would like to annotate STRING "source based".

**Comment by federicomarini** [comment]
Excellent, if possible we could strive to stick to the "vendor-provided" annotation, while we keep the orgDb annotation one as a close-to-perfect plan B.

Benefits: no need to guess which version was used at the moment of releasing the resource, in case the identifier matching would vary over time for whatever reasons.

**Comment by lottawagner** [comment]
used the protein.aliases file provided by STRING to annotate :) works for "Homo sapiens" "v12.0" so far
